- name: download solana-installer
  get_url:
    url: "https://release.anza.xyz/{{ solana_installer_version }}/install"
    dest: /usr/local/sbin/solana-install-init.sh
    force: yes
    mode: 0755
    owner: root
    group: root
#    checksum: "{{ solana_checksums[solana_installer_version] }}"

- name: install solana
  shell: "/usr/local/sbin/solana-install-init.sh"
  args:
    chdir: /home/solana/
  become: true
  become_user: solana
  register: install_output
  changed_when: false

- name: debug
  debug: var=install_output

- name: ensure solana storage directories are available
  file:
    path: "{{ item }}"
    owner: solana
    group: solana
    mode: 0755
    state: directory
  with_items:
    - "/home/solana/bin"
    - "/home/solana/src"
    - "/home/solana/geyser"
    - "{{ solana_root }}"
    - "{{ solana_ledger_location }}"
    - "{{ solana_ledger_location }}/rocksdb"
    - "{{ solana_accounts_location }}"

- name: clone solana src
  git:
    repo: https://github.com/rpcpool/yellowstone-grpc.git
    dest: /home/solana/geyser/yellowstone-grpc
    clone: true
  become: true
  become_user: solana
